<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>BombRushMP.Plugin</AssemblyName>
    <Description>My first plugin</Description>
    <Version>1.7.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release;Developer Debug</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <ManagedPath>$(BRCPath)/Bomb Rush Cyberfunk_Data/Managed</ManagedPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Developer Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="res\**" />
    <EmbeddedResource Remove="res\**" />
    <None Remove="res\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.27" IncludeAssets="compile" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BombRushMP.BunchOfEmotes\BombRushMP.BunchOfEmotes.csproj" />
    <ProjectReference Include="..\BombRushMP.Common\BombRushMP.Common.csproj" />
    <ProjectReference Include="..\BombRushMP.CrewBoom\BombRushMP.CrewBoom.csproj" />
    <ProjectReference Include="..\BombRushMP.MapStation\BombRushMP.MapStation.csproj" />
    <ProjectReference Include="..\BombRushMP.Mono\BombRushMP.Mono.csproj" />
    <ProjectReference Include="..\BombRushMP.NetRadio\BombRushMP.NetRadio.csproj" />
    <ProjectReference Include="..\BombRushMP.NetworkInterfaceProvider\BombRushMP.NetworkInterfaceProvider.csproj" />
    <ProjectReference Include="..\BombRushMP.PluginCommon\BombRushMP.PluginCommon.csproj" />
    <ProjectReference Include="..\BombRushMP.Server\BombRushMP.Server.csproj" />
    <ProjectReference Include="..\libs\BRC-CommonAPI\CommonAPI.csproj">
      <Private>False</Private>
      <CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedPath)/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ManagedPath)/Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>$(ManagedPath)/Unity.Timeline.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(ManagedPath)/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="EasyDecal.Runtime">
      <HintPath>$(ManagedPath)/EasyDecal.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>$(ManagedPath)/Rewired_Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
</Project>